#!/bin/bash

#ifconfig wlan0 up

systemctl stop wpa_supplicant

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/configuration_app/app.py &

hostapd -dd /etc/hostapd/hostapd.conf &
